### ISSUE TITLE
GCL_HICON not found in file ResizableFormViewMDI\DemoView.cpp ...

### ISSUE THREAD

**Issue by 0ric1** [ppescher/resizablelib#15]
should it be IDC_ICON1?

**Comment by ppescher** [comment]
Nope, it's a windows constant used in calls to GetClassLong().
What exactly is the error you are getting?

**Comment by ppescher** [comment]
I don't remember why it was that way, but I think it is trying to show a different icon depending on the parent frame the view is loaded into.

See: https://github.com/ppescher/resizablelib/search?q=GCL_HICON&type=Code

**Comment by 0ric1** [comment]
> What exactly is the error you are getting?
I was building (Build / Batch Build - Select All / Rebuild) with Visual Studio 2019 16.3 Preview 2 (I did not upgrade the projects). At work I don't get the error - need to try it again at home.

**Comment by 0ric1** [comment]
I found the problem: at work I have VS 2017 and VS 2019 installed at home only the newest VS 2019 Preview. The installer of VS 2019 has only the "C++-Windows XP ... 2017 .. v141" available for installation - no more "XP ... 2015 .. v140", but the projects needs "... 2015 ... v140".
So my fault - sorry.
