### ISSUE TITLE
InitThemeSettings can be simplyfied on Vista and later ...

### ISSUE THREAD

**Issue by 0ric1** [ppescher/resizablelib#22]
The function InitThemeSettings in ResizableVersion.cpp can be simplyfied on Vista and later, because GetThemeAppProperties and IsAppThemed is available:

`
...
  if (!IsAppThemed())
    return;

  real_ThemeSettings = GetThemeAppProperties();
...
`

**Comment by irwir** [comment]
The gain is insignificant, but breaks compatibility with earlier Windows versions.

**Comment by ppescher** [comment]
I know old Windows versions are no longer supported by Microsoft, but I would like to keep compatibility when possible.

**Comment by 0ric1** [comment]
You could add #if WINVER >= _WIN32_WINNT_WIN6 than new code else old code.

**Comment by irwir** [comment]
POSReady  was obsoleted only in April of 2019, while VS2017 is still getting updates and still can build for XP.

@Blonder 
> You could add #if WINVER >= _WIN32_WINNT_WIN6 than new code else old code.

It was already taken care of programmatically in the existing code.
Conditional compilation would mean adding more source lines while trying to save a handful of bytes in binary code.
