### ISSUE TITLE
Flicker on TabCtrl while dragging window

### ISSUE THREAD

**Issue by adipose** [ppescher/resizablelib#30]
See https://github.com/clsid2/mpc-hc/pull/2823/commits/e30cca9a3639943465cdad4ff1c3ffedebb64da1 for a fix I did for mpc-hc.

Basically, the `MoveWindow` calls seem to trigger an erasebackground, which causes significant flickers.

**Comment by ppescher** [comment]
Thanks for reporting this.
Please see commit https://github.com/ppescher/resizablelib/commit/25a89da6e15b0d97f2347947c747ce50e549a20c

**Comment by adipose** [comment]
Awesome, thank you!

My goal is to use resizelib without mods in mpc-hc.  I may have some other requests.
