### ISSUE TITLE
Question: how does resizelib respond to existing gripper?

### ISSUE THREAD

**Issue by adipose** [ppescher/resizablelib#33]
`CStatusBar` can have style `SBARS_SIZEGRIP`, which creates a gripper in the bottom right of the statusbar.

What does resizelib do in this case?  Does it just draw on top of it?

I tried to disable the gripper from resizelib, but I realized it was being drawn by win32, as well.

**Comment by ppescher** [comment]
Never tried on a dialog box, but in SDI applications the sizegrip is hidden. You can hide it too in dialogs. Of course the status bar will show its own sizegrip.

**Comment by adipose** [comment]
It doesn't matter much but I wonder if disabling it from resizelib should update the CStatusBar style to match?

**Comment by ppescher** [comment]
I guess it is the responsibility of the final dialog class, which creates the CStatusBar, to disable the CResizableSizeGrip and use only the status bar.

**Comment by adipose** [comment]
OK, thank you for documenting that here.  In my experience, it works fine as-is, but I was confused when I realized there were two things drawing the same gripper.
